baseURL = "https://juguetes.tole.es"
languageCode = "es-es"
title = "Los Ãºltimos descuentos detectados!"
theme = "hugo-shopping-product-catalogue-simple"

[Params]
description = "Descuentos en juguetes"
channel = "https://t.me/s/estodojuguetes"
ga = "G-GFQQ3HZ9KL"
yandex = "d953d3bd2561b908"

[sitemap]
  changefreq = "daily"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "RSS"]